#!/bin/bash

#----------------------------------------------------------------------------
#
# mpi run script
#
# Copyright (c) 2009 Han-Wei Shen and Tom Peterka
#
# Contact:
#
# Han-Wei Shen
# The Ohio State University
# Columbus, OH
#
# Tom Peterka
# MCS Radix Lab
# Argonne National Laboratory
# 9700 S. Cass Ave.
# Argonne, IL 60439
# tpeterka@mcs.anl.gov
#
# All rights reserved. May not be used, modified, or copied
# without permission
#
#----------------------------------------------------------------------------
ARCH=LINUX
#ARCH=BGP
#ARCH=FD
#ARCH=EUREKA
#ARCH=BB

# number of BG/P nodes
nodes=64

# number of procs
num_procs=1

# executable
exe=./mpitest

# dataset
if [ "$ARCH" = "LINUX" ]; then
#data=/homes/tpeterka/tornado/tornado.list # path on my linux box
#data=/Users/troot/tornado/tornado.list # path on my mac
data=/homes/tpeterka/plume/plume.list

fi
if [ "$ARCH" = "BGP" ]; then
data=/home/tpeterka/plume/plume.list
fi

# data size x y z t
# (for static flow use t = 1 and list one time step in the dataset file)
#dsize="128 128 128 1" # for tornado
dsize="126 126 512 5" # for plume

# total number of partitions in the space domain
sb=8

# total number of partitions in the time domain
tb=5

# number of time partitions per time group
tr=1

# number of traces per block
t=5

# number of points per trace
p=50

# number of rounds per time group
r=5

# number of threads
# 1 = each process a single thread
# 2 = each process two threads: compute and I/O
th=1

# available memory space for dataset (MB)
m=128

# partition file
if [ "$ARCH" = "LINUX" ]; then
#pf=/homes/tpeterka/plume/partitions-npart16-blocksize32-15plume3d421.bin
pf=! # indicates no partition file
fi
if [ "$ARCH" = "BGP" ]; then
pf=/home/tpeterka/plume/partitions-npart16-blocksize32-15plume3d421.bin
#pf=! # indicates no partition file
fi

# data mode
# 0 = raw with no header data
# 1 = raw with dimensions at start
# 2 = netCDF
# 3 = HDF5
dm=0

if [ "$ARCH" = "LINUX" ]; then

mpiexec -l -n $num_procs $exe $data $dsize $sb $tb $tr $t $p $r $th $m $pf $dm

#mpiexec -l -n $num_procs valgrind -q --leak-check=yes $exe $data $dsize $sb $tb $tr $t $p $r $th $m $pf $dm

#mpiexec -l -n $num_procs valgrind -q $exe $data $dsize $sb $tb $tr $t $p $r $th $m $pf $dm

#mpiexec  -n $num_procs xterm -e gdb -x gdb.run --args $exe $data $dsize $sb $tb $tr $t $p $r $th $m $pf $dm

fi

if [ "$ARCH" = "BGP" ]; then

pvfs2-drop-caches -m /pvfs-surveyor
cqsub -n $num_procs -c $num_procs -p UltraVis -t 10 -m smp $exe $data $dsize $sb $tb $tr $t $p $r $th $m $pf $dm

fi

if [ "$ARCH" = "FD" ]; then

srun -l -p scx-comp -N $num_procs -n $num_procs $exe $data $dsize $sb $tb $tr $t $p $r $th $m $pf $dm

fi

if [ "$ARCH" = "EUREKA" ]; then

pvfs2-drop-caches -m /pvfs-surveyor
mpirun -np $num_procs -machinefile $COBALT_NODEFILE $exe $data $dsize $sb $tb $tr $t $p $r $th $m $pf $dm

fi

if [ "$ARCH" = "BB" ]; then

mpiexec -machinefile ./nodes -l -n $num_procs $exe $data $dsize $sb $tb $tr $t $p $r $th $m $pf $dm

#mpiexec -machinefile ./nodes -l -n $num_procs hostname

fi

