#!/bin/bash

#----------------------------------------------------------------------------
#
# mpi run script
#
# Copyright (c) 2009 Han-Wei Shen and Tom Peterka
#
# Contact:
#
# Han-Wei Shen
# The Ohio State University
# Columbus, OH
#
# Tom Peterka
# MCS Radix Lab
# Argonne National Laboratory
# 9700 S. Cass Ave.
# Argonne, IL 60439
# tpeterka@mcs.anl.gov
#
# All rights reserved. May not be used, modified, or copied
# without permission
#
#----------------------------------------------------------------------------

# number of procs
num_procs=4

# executable
exe=./mpitest

# dataset
data=./plume1.vec

# data size
dsize="126 126 512"

# number of blocks per process
b=4

# number of traces per block
t=20

# number of points per trace
p=100

# number of iterations
n=3

mpiexec -l -n $num_procs $exe $data $dsize $b $t $p $n

#mpiexec -l -n $num_procs valgrind -q $exe $data $dsize $b $t $p $n

#mpiexec  -n $num_procs xterm -e gdb -x gdb.run --args $exe $data $dsize $b $t $p $n


