#!/bin/bash

#----------------------------------------------------------------------------
#
# mpi run script
#
# Copyright (c) 2009 Han-Wei Shen and Tom Peterka
#
# Contact:
#
# Han-Wei Shen
# The Ohio State University
# Columbus, OH
#
# Tom Peterka
# MCS Radix Lab
# Argonne National Laboratory
# 9700 S. Cass Ave.
# Argonne, IL 60439
# tpeterka@mcs.anl.gov
#
# All rights reserved. May not be used, modified, or copied
# without permission
#
#----------------------------------------------------------------------------

# number of procs
num_procs=8

# executable
exe=./mpitest

# dataset
data=~hwshen/tornado/tornado.list

# data size x y z t (for steady state flows use t = 1)
dsize="128 128 128 20"

# total number of spatial blocks
sb=8

# total number of temporal blocks
tb=1

# number of traces per block
t=100

# number of points per trace
p=100

# number of iterations
n=3

mpiexec -l -n $num_procs $exe $data $dsize $sb $tb $t $p $n

#mpiexec -l -n $num_procs valgrind -q --leak-check=yes $exe $data $dsize $sb $tb $t $p $n

#mpiexec  -n $num_procs xterm -e gdb -x gdb.run --args $exe $data $dsize $sb $tb $t $p $n


