#!/bin/bash

#----------------------------------------------------------------------------
#
# mpi run script
#
# Copyright (c) 2009 Han-Wei Shen and Tom Peterka
#
# Contact:
#
# Han-Wei Shen
# The Ohio State University
# Columbus, OH
#
# Tom Peterka
# MCS Radix Lab
# Argonne National Laboratory
# 9700 S. Cass Ave.
# Argonne, IL 60439
# tpeterka@mcs.anl.gov
#
# All rights reserved. May not be used, modified, or copied
# without permission
#
#----------------------------------------------------------------------------
ARCH=LINUX
#ARCH=BGP
#ARCH=FD
#ARCH=EUREKA
#ARCH=BB

# number of BG/P nodes
nodes=64

# number of procs
num_procs=2

# executable
exe=./mpitest

# dataset
data=~tpeterka/flash/8km_16o40_bin_cnt_0400

# data size x y z t (for steady state flows use t = 1)
# for amr, can use all 1's, or whatever (finds its own size)
dsize="1 1 1 1"

# total number of partitions in the space domain
sb=1

# total number of partitions in the time domain
# for steady state flows use tb = 1
tb=1

# number of time partitions per round
tr=1

# number of traces per block
t=1

# number of points per trace
p=10

# number of rounds
r=1

# number of threads
# 1 = each process a single thread
# 2 = each process two threads: compute and I/O
th=1

# available memory space for dataset (MB)
m=1024

if [ "$ARCH" = "LINUX" ]; then

mpiexec -l -n $num_procs $exe $data $dsize $sb $tb $tr $t $p $r $th $m

#mpiexec -l -n $num_procs valgrind -q --leak-check=yes $exe $data $dsize $sb $tb $tr $t $p $r $th $m

#mpiexec -l -n $num_procs valgrind -q $exe $data $dsize $sb $tb $tr $t $p $r $th $m

#mpiexec  -n $num_procs xterm -e gdb -x gdb.run --args $exe $data $dsize $sb $tb $tr $t $p $r $th $m

fi

if [ "$ARCH" = "BGP" ]; then

cqsub -n $num_procs -c $num_procs -p UltraVis -t 10 -m smp $exe $data $dsize $sb $tb $tr $t $p $r $th $m

fi

if [ "$ARCH" = "FD" ]; then

srun -l -p scx-comp -N $num_procs -n $num_procs $exe $data $dsize $sb $tb $tr $t $p $r $th $m

fi

if [ "$ARCH" = "EUREKA" ]; then

mpirun -np $num_procs -machinefile $COBALT_NODEFILE $exe $data $dsize $sb $tb $tr $t $p $r $th $m

fi

if [ "$ARCH" = "BB" ]; then

mpiexec -machinefile ./nodes -l -n $num_procs $exe $data $dsize $sb $tb $tr $t $p $r $th $m

#mpiexec -machinefile ./nodes -l -n $num_procs hostname

fi
