#!/bin/bash

#------------------------------------------------------------------------------
#
# mpi run script
#
# Copyright (c) 2008 Han-Wei Shen and Tom Peterka
#
# Contact:
#
# Han-Wei Shen
# The Ohio State University
# Columbus, OH
#
# Tom Peterka
# MCS Radix Lab
# Argonne National Laboratory
# 9700 S. Cass Ave.
# Argonne, IL 60439
# tpeterka@mcs.anl.gov
#
# All rights reserved. May not be used, modified, or copied
# without permission
#
#------------------------------------------------------------------------------

#cd ~/osuflow

# number of procs
num_procs=2

# executable
#exe=./mpitest
exe=./drawtest

# dataset
data=./plume.vec

# data size
dsize="126 126 512"

# blocking factor
bf=2

/soft/apps/packages/mpich2-1.0.7rc1-gcc/bin/mpiexec -n $num_procs $exe $data $dsize $bf


