#!/bin/bash

#----------------------------------------------------------------------------
#
# serial run script
#
# Copyright (c) 2009 Han-Wei Shen and Tom Peterka
#
# Contact:
#
# Han-Wei Shen
# The Ohio State University
# Columbus, OH
#
# Tom Peterka
# MCS Radix Lab
# Argonne National Laboratory
# 9700 S. Cass Ave.
# Argonne, IL 60439
# tpeterka@mcs.anl.gov
#
# All rights reserved. May not be used, modified, or copied
# without permission
#
#----------------------------------------------------------------------------
# executable
exe=./sertest

# dataset
data=/homes/tpeterka/tornado/tornado.list
#data=/homes/tpeterka/plume/plume.list

# data size x y z t
# (for static flow use t = 1 and list one time step in the dataset file)
dsize="128 128 128 32" #tornado
#dsize="126 126 512 4" #plume

# total number of partitions in the space domain
sb=8

# total number of partitions in the time domain
tb=1

# number of time partitions per time group
tr=1

# number of traces per block
t=1

# number of points per trace
p=50

# number of rounds per time group
r=5

# data mode
# 0 = raw with no header data
# 1 = raw with dimensions at start
# 2 = netCDF
# 3 = HDF5
dm=0

$exe $data $dsize $sb $tb $tr $t $p $r $dm

#valgrind -q $exe $data $dsize $sb $tb $tr $t $p $r $dm

#valgrind -q --leak-check=yes $exe $data $dsize $sb $tb $tr $t $p $r $dm

#gdb -x gdb.run --args $exe $data $dsize $sb $tb $tr $t $p $r $dm
