#!/bin/bash

#----------------------------------------------------------------------------
#
# serial run script
#
# Copyright (c) 2009 Han-Wei Shen and Tom Peterka
#
# Contact:
#
# Han-Wei Shen
# The Ohio State University
# Columbus, OH
#
# Tom Peterka
# MCS Radix Lab
# Argonne National Laboratory
# 9700 S. Cass Ave.
# Argonne, IL 60439
# tpeterka@mcs.anl.gov
#
# All rights reserved. May not be used, modified, or copied
# without permission
#
#----------------------------------------------------------------------------
# executable
exe=./seramrtest

# dataset
data=/homes/tpeterka/flash/flash.list

# data size x y z t
# use x = y = z = 1 (finds its own spatial size)
# use t = # of timesteps (static flow use t = 1 and list one time step in the 
# dataset file)
dsize="1 1 1 1"

# total number of partitions in the space domain
sb=1

# total number of partitions in the time domain
# for steady state flows use tb = 1
tb=1

# number of traces per block
t=1

# number of points per trace
p=10

# number of rounds
r=5

$exe $data $dsize $sb $tb $t $p $r

#valgrind -q $exe $data $dsize $sb $tb $t $p $r

#valgrind -q --leak-check=yes $exe $data $dsize $sb $tb $t $p $r

#gdb -x gdb.run --args $exe $data $dsize $sb $tb $t $p $r
