#!/bin/bash

#----------------------------------------------------------------------------
#
# mpi run script
#
# Tom Peterka
# Argonne National Laboratory
# 9700 S. Cass Ave.
# Argonne, IL 60439
# tpeterka@mcs.anl.gov
#
# All rights reserved. May not be used, modified, or copied
# without permission
#
#----------------------------------------------------------------------------
ARCH=MAC_OSX
#ARCH=LINUX
#ARCH=BGP
#ARCH=EUREKA

# number of procs
num_procs=4

# number of BG/P nodes
num_nodes=$[$num_procs / 4]

# executable
exe=./mpiamrtest

# dataset
if [ "$ARCH" = "LINUX" ] || [ "$ARCH" = "MAC_OSX" ]; then
#data=$HOME/flash/flash.list
data=$HOME/cosmo/cosmo.list

fi
if [ "$ARCH" = "BGP" ]; then
data=/pvfs-surveyor/tpeterka/flash/flash.list
fi

# total number of temporal blocks
tb=1

# total number of particles
t=2048
#t=10520

# number of points per trace
p=1000

# number of rounds per time group
r=100

# data mode
# 0 = raw with no header data
# 1 = raw with dimensions at start
# 2 = netCDF
# 3 = HDF5 float (32 bit)
# 4 = HDF5 double (64 bit)
dm=4

# velocity variable names
vx=velx
vy=vely
vz=velz

# all program args
args="$data $tb $t $p $r $dm $vx $vy $vz"

if [ "$ARCH" = "MAC_OSX" ]; then

mpiexec -l -n $num_procs $exe $args
#dsymutil ./mpiamrtest; mpiexec -l -n $num_procs xterm -e gdb -x gdb.run --args $exe $args
#dsymutil ./mpiamrtest; mpiexec -l -n $num_procs valgrind -q $exe $args

fi

if [ "$ARCH" = "LINUX" ]; then

mpiexec -n $num_procs $exe $args
#mpiexec -n $num_procs valgrind -q --leak-check=yes $exe $args
#mpiexec -n $num_procs valgrind -q $exe $args
#mpiexec -n $num_procs xterm -e gdb -x gdb.run --args $exe $args

fi

if [ "$ARCH" = "BGP" ]; then

pvfs2-drop-caches -m /pvfs-surveyor
cqsub -n $num_procs -c $num_procs -p UltraVis -t 10 -m smp $exe $args

fi

if [ "$ARCH" = "EUREKA" ]; then

mpirun -np $num_procs -machinefile $COBALT_NODEFILE $exe $args

fi
