#!/bin/bash

#----------------------------------------------------------------------------
#
# serial run script
#
# Han-Wei Shen
# The Ohio State University
# Columbus, OH
#
# Tom Peterka
# Argonne National Laboratory
# 9700 S. Cass Ave.
# Argonne, IL 60439
# tpeterka@mcs.anl.gov
#
# All rights reserved. May not be used, modified, or copied
# without permission
#
#----------------------------------------------------------------------------
# executable
exe=./seramrtest

# dataset
#data=$HOME/flash/flash.list
data=$HOME/cosmo/cosmo.list

# total number of partitions in the time domain
# (ignored for static flow)
tb=1

# total number of particles
tp=1

# data mode
# 0 = raw with no header data
# 1 = raw with dimensions at start
# 2 = netCDF
# 3 = HDF5 float (32 bit)
# 4 = HDF5 double (64 bit)
#dm=3
dm=4

# velocity variable names
vx=velx
vy=vely
vz=velz

args="$data $tb $tp $dm $vx $vy $vz"
$exe $args

#valgrind -q $exe $args

#valgrind -q --leak-check=yes $exe $args

#gdb -x gdb.run --args $exe $args
