#!/bin/bash

#----------------------------------------------------------------------------
#
# mpi run script
#
# Tom Peterka
# Argonne National Laboratory
# 9700 S. Cass Ave.
# Argonne, IL 60439
# tpeterka@mcs.anl.gov
#
# All rights reserved. May not be used, modified, or copied
# without permission
#
#----------------------------------------------------------------------------

# number of procs
num_procs=4

# executable
exe=../../Regular/Parallel/mpitest

# dataset
data=$HOME/osuflow/sample_data/regular/test.list

# number of spatial blocks per process
bf=4

# total number of temporal blocks
tb=1

# total number of particles
t=50

# number of points per trace
p=1000

# number of rounds per time group
r=20

# partition file
pf=! # indicates no partition file

# data mode
# 0 = raw with no header data
# 1 = raw with dimensions at start
# 2 = netCDF
# 3 = HDF5 float (32 bit)
# 4 = HDF5 double (64 bit)
dm=0

mpiexec -l -n $num_procs $exe $data $bf $tb $t $p $r $pf $dm

